version: "2"
services:
  certbot:
    image: fake-certbot-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - EMAIL=renkeju@gmail.com
      - DOMAIN=renkeju.com
    volumes:
      - ./letsencrypt/:/etc/letsencrypt/
      - ./log/:/var/log/letsencrypt/